CREATE TABLE IF NOT EXISTS je_leads (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  lead_uuid CHAR(36) NOT NULL,
  student_name VARCHAR(120) NOT NULL,
  phone VARCHAR(20) NOT NULL,
  email VARCHAR(190) NOT NULL,
  city VARCHAR(100) DEFAULT NULL,
  qualification VARCHAR(120) DEFAULT NULL,
  interested_course VARCHAR(190) NOT NULL,
  preferred_mode VARCHAR(50) DEFAULT NULL,
  preferred_location VARCHAR(120) DEFAULT NULL,
  preferred_batch VARCHAR(80) DEFAULT NULL,
  message TEXT DEFAULT NULL,
  contact_consent TINYINT(1) NOT NULL DEFAULT 0,
  source_domain VARCHAR(190) DEFAULT NULL,
  source_page VARCHAR(255) DEFAULT NULL,
  page_title VARCHAR(255) DEFAULT NULL,
  student_segment VARCHAR(100) DEFAULT NULL,
  landing_page VARCHAR(255) DEFAULT NULL,
  referrer VARCHAR(500) DEFAULT NULL,
  utm_source VARCHAR(150) DEFAULT NULL,
  utm_medium VARCHAR(150) DEFAULT NULL,
  utm_campaign VARCHAR(190) DEFAULT NULL,
  utm_term VARCHAR(190) DEFAULT NULL,
  utm_content VARCHAR(190) DEFAULT NULL,
  ip_hash CHAR(64) DEFAULT NULL,
  user_agent VARCHAR(500) DEFAULT NULL,
  status VARCHAR(30) NOT NULL DEFAULT 'new',
  duplicate_count INT UNSIGNED NOT NULL DEFAULT 0,
  last_seen_at DATETIME DEFAULT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uq_je_leads_uuid (lead_uuid),
  KEY idx_je_leads_phone (phone),
  KEY idx_je_leads_course (interested_course),
  KEY idx_je_leads_created (created_at),
  KEY idx_je_leads_ip_hash (ip_hash)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
